package storage

import (
	"context"
	"testing"
)

// Only reviewed match candidates (confirmed/rejected) protect a work from
// automatic cleanup: they record a user decision. A pending 'candidate'
// match was generated automatically and never reviewed, so it does not
// protect; it is cascaded away with the work and can be regenerated by the
// next enrichment pass. Protected unreferenced works appear in the
// management list instead of being deleted.
func TestCleanupAutoWorksProtectsMatchCandidates(t *testing.T) {
	t.Run("rejected", func(t *testing.T) {
		s, ctx, _ := albumWorkFixture(t, "Unknown Album", "Track")
		workID := insertAutoWorkWithCandidate(t, s, ctx, "rejected")
		var stats RefreshStats
		if e := s.CleanupAutoWorks(ctx, &stats); e != nil {
			t.Fatal(e)
		}
		if stats.WorksDeleted != 0 || stats.ProtectedUnreferenced != 1 {
			t.Fatalf("cleanup stats %+v", stats)
		}
		assertCandidateState(t, s, ctx, workID, "rejected", 1, true)
	})
	t.Run("confirmed", func(t *testing.T) {
		s, ctx, _ := albumWorkFixture(t, "Unknown Album", "Track")
		workID := insertAutoWorkWithCandidate(t, s, ctx, "confirmed")
		var stats RefreshStats
		if e := s.CleanupAutoWorks(ctx, &stats); e != nil {
			t.Fatal(e)
		}
		if stats.WorksDeleted != 0 || stats.ProtectedUnreferenced != 1 {
			t.Fatalf("cleanup stats %+v", stats)
		}
		assertCandidateState(t, s, ctx, workID, "confirmed", 1, true)
	})
	t.Run("candidate only is cleaned up", func(t *testing.T) {
		s, ctx, _ := albumWorkFixture(t, "Unknown Album", "Track")
		workID := insertAutoWorkWithCandidate(t, s, ctx, "candidate")
		var stats RefreshStats
		if e := s.CleanupAutoWorks(ctx, &stats); e != nil {
			t.Fatal(e)
		}
		if stats.WorksDeleted != 1 || stats.ProtectedUnreferenced != 0 {
			t.Fatalf("cleanup stats %+v", stats)
		}
		assertCandidateState(t, s, ctx, workID, "candidate", 0, false)
	})
}

func insertAutoWorkWithCandidate(t *testing.T, s *Store, ctx context.Context, status string) int64 {
	t.Helper()
	result, e := s.db.ExecContext(ctx, `INSERT INTO works(title,normalized_title,type,origin) VALUES(?,?,?,'auto')`, "Pending "+status, "pending "+status, "other")
	if e != nil {
		t.Fatal(e)
	}
	workID, _ := result.LastInsertId()
	if _, e = s.db.ExecContext(ctx, `INSERT INTO work_match_candidates(work_id,source,external_id,title,score,status) VALUES(?,'bangumi',?,?,0,?)`, workID, "ext-"+status, "Pending "+status, status); e != nil {
		t.Fatal(e)
	}
	return workID
}

func assertCandidateState(t *testing.T, s *Store, ctx context.Context, workID int64, status string, wantCandidates int, listed bool) {
	t.Helper()
	var candidates int
	if e := s.db.QueryRowContext(ctx, `SELECT COUNT(*) FROM work_match_candidates WHERE work_id=? AND status=?`, workID, status).Scan(&candidates); e != nil || candidates != wantCandidates {
		t.Fatalf("candidates=%d, want %d (err %v)", candidates, wantCandidates, e)
	}
	works, total, e := s.UnreferencedProtectedWorks(ctx)
	if e != nil {
		t.Fatal(e)
	}
	found := false
	for _, w := range works {
		if w.ID == workID {
			found = true
		}
	}
	if found != listed {
		t.Fatalf("protected unreferenced list contains work=%v, want %v (list %+v total=%d)", found, listed, works, total)
	}
}
